  sudo: required
  services:
    - docker

  script:
    - docker build -t gabrielrueda/node .
    - docker images gabrielrueda/node

  before_deploy:
    - docker login -u gabrielrueda -p Anguiano01*

  deploy:
    provider: script
    script: docker push gabrielrueda/node
    on:
        branch: master